#!/bin/bash

module load bowtie2/2.3.3.1

# Get the current directory path
sample_directory="/hpc/group/G_MICRO/DOPnonDOP_noema/01_AdpRem_output"

# Create output directory
output_dir="/hpc/group/G_MICRO/DOPnonDOP_noema/02_Bowtie2_output"
mkdir -p "$output_dir"

# Loop through files matching the pattern FILE_cleaned_R1.fq.gz
for file_L1 in "$sample_directory"/*cleaned_L1.fq.gz; do
    # Check if at least one R1 file is present
    if [ -e "$file_L1" ]; then
        # Generate the corresponding R2 file name
        file_L2="${file_L1/_L1/_L2}"
        
        # Run bowtie2 with the current file names
        bowtie2 -x /hpc/group/G_MICRO/Metagenomica-database/Bos_taurus/Bos_taurus.bt2 \
		-1 "$file_L1" -2 "$file_L2" \
	        -q --phred33 --local \
                --un-conc-gz "$output_dir/$(basename "${file_L1/_cleaned_L1.fq.gz/.fq.gz}")" \
                -p 32 -S "$output_dir/$(basename "${file_L1/_cleaned_L1.fq.gz/.sam}")"

        # Remove the .sam file generated by Bowtie2
        rm "$output_dir/$(basename "${file_L1/_cleaned_L1.fq.gz/.sam}")"
    fi
done