step00_01:
  dir1: "../../input/@input_sample@"
  dir2: "../../output/@output_folder@/01_AdapterRemoval"
  dir3: "../../output/@output_folder@/01_AdapterRemoval"
  dir4: "X204SC24020161-Z01-F003_01.tar"
  dir5: "X204SC24020161-Z01-F003_02.tar"
  par1: 80
  par2: 50
  par3: 30
  par4: 10
  par5: 2
  par6: 2

step02:
  reference_genome: "/hpc/home/luca.bettera/Downloads/ncbi_dataset/data/GCA_002263795.4/GCA_002263795.4_ARS-UCD2.0_genomic.fna Bos_taurus"

step03:
  dir1: "../../output/@output_folder@/01_AdapterRemoval"
  dir2: "../../output/@output_folder@/03_bowtie2_output"
  dir3: "../../data/gene/Bos_taurus/Bos_taurus"

step04:
  #dir1: "../../data/metaphlan_database"
  dir2: "../../output/@output_folder@/03_bowtie2_output"
  dir3: "../../output/@output_folder@/04_metaphlan_output"
  rscript: "../../data/calculate_diversity.R"
  
step04b_1:
  dir1: "../../output/@output_folder@/04_metaphlan_output"
  dir2: "../../output/@output_folder@/03_bowtie2_output"
  dir3: "../../output/@output_folder@/04b_humann_output"

step04b_2:
  dir1: "../../output/@output_folder@/04_metaphlan_output"
  dir2: "../../output/@output_folder@/03_bowtie2_output"
  dir3: "../../output/@output_folder@/04b_humann_output"
  
step04b_last:
  dir1: "../../output/@output_folder@/04b_humann_output"
  dir2: "../../output/@output_folder@/04b_humann_output/merged_tables"

step05:
  var1: "../../output/@output_folder@/03_bowtie2_output"
  var2: "../../output/@output_folder@/05_spades_output"
  par1: 24
  par2: 200

step06:
  var1: "../../output/@output_folder@/05_spades_output"
  var2: "contigs"
  var3: "filtered"
  filter1: 32

step07:
  dir1: "../../output/@output_folder@/07_Bowtie_Index"
  dir2: "../../output/@output_folder@/05_spades_output/contigs/filtered"
  par1: 24

step08_09:
  dir1: "../../output/@output_folder@/03_bowtie2_output"
  dir2: "../../output/@output_folder@/07_Bowtie_Index"
  dir3: "../../output/@output_folder@/08_mapping_coverage"

step10_11:
  dir1: "../../output/@output_folder@/08_mapping_coverage"
  dir2: "../../output/@output_folder@/10_metabat_depth"
  dir3: "../../output/@output_folder@/05_spades_output/contigs/filtered"
  dir4: "../../output/@output_folder@/11_metabat_MAG"
  dir5: "../../output/@output_folder@/11b_metabat_MAG"
  par1: 1500
  par2: 200

step12_13:
  var1: "../../output/@output_folder@/11_metabat_MAG"
  var2: "../../output/@output_folder@/12_checkm"
  var3: "../../output/@output_folder@/13_checkm2"
  par1: 20
  par2: 4
  par3: 24

step14:
  var1: "../../output/@output_folder@/13_checkm2/quality_report.tsv"
  var2: "../../output/@output_folder@/11_metabat_MAG"
  var3: "../../output/@output_folder@/14_MAGs_high_quality"
  var4: "../../output/@output_folder@/14_MAGs_high_quality"
  var5: 50
  var6: 10
  var7: "my-metadata2.txt"
  var8: "all_metadata.tsv"

step15:
  var1: "../../output/@output_folder@"
  var2: "14_MAGs_high_quality/my-metadata2.txt"
  par1: "15_tormes_MAGs/"
  par2: 24
